name: 同步仓库（不含子模块）

on:
  push:
    branches: [ master ]  # 根据你的默认分支修改

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 检出源仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史
        token: ${{ secrets.SYNC_TOKEN }}

    - name: 配置Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: 移除子模块
      run: |
        # 移除子模块目录
        rm -rf assets/resource
        
        # 移除.gitmodules文件
        rm -f .gitmodules
        
        # 如果.git/config中有子模块配置，也移除它
        git config --local --unset-all submodule.assets/resource.url || true
        git config --local --unset-all submodule.assets/resource.active || true

    - name: 移除同步工作流
      run: |
        # 移除同步工作流文件，避免无限循环
        rm -f .github/workflows/sync-repo.yml
        
        # 提交变更
        git add -A
        git commit -m "从 TanyaShue/MaaYYs 同步 - ${GITHUB_SHA}"

    - name: 推送到目标仓库
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SYNC_TOKEN }}
        repository: TanyaShue/MFWPH
        branch: master
        force: true

    - name: 推送当前标签（如果有）
      if: success()  # 仅当之前的步骤成功时执行
      run: |
        # 检查当前提交是否有标签
        CURRENT_TAGS=$(git tag --points-at HEAD)
        if [ -n "$CURRENT_TAGS" ]; then
          # 创建一个临时目录
          mkdir -p ~/temp_repo && cd ~/temp_repo
          
          # 克隆目标仓库（浅克隆以提高速度）
          git clone --depth 1 https://${{ secrets.SYNC_TOKEN }}@github.com/TanyaShue/MFWPH.git .
          
          # 配置Git
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          # 为每个标签创建一个新的标签指向目标仓库的HEAD
          for tag in $CURRENT_TAGS; do
            echo "创建标签: $tag"
            git tag -f "$tag" HEAD
          done
          
          # 推送标签
          git push --tags --force
        else
          echo "当前提交没有标签，跳过标签推送"
        fi